### ISSUE TITLE
README send array example does not work

### ISSUE THREAD

**Issue by jarmitage** [colinbdclark/osc.js#102]
This example in `README.md`:
- `"/float/andArray" ",f[ff]" 440.4 42 47`
```javascript
{
    address: "/carrier/freq",
    args: [
        {
            type: "f",
            value: 440.4
        },
        {
            type: "[ff]",
            value: [42.0, 47.0]
        }
    ]
}
```

Produces this error:

```javascript
Sending message /carrier/freq [ { type: 'f', value: 440.4 },
  { type: '[ff]', value: [ 42, 47 ] } ] to 127.0.0.1:57120
Error:  Cannot read property 'writer' of undefined
/.../node_modules/osc/src/osc.js:119
                new Buffer(obj.buffer ? obj : new Uint8Array(obj));
                               ^
TypeError: Cannot read property 'buffer' of undefined
    at Object.osc.nativeBuffer (/.../node_modules/osc/src/osc.js:119:32)
    at osc.UDPPort.p.send (/.../node_modules/osc/src/osc-transports.js:55:23)
    at Timeout._onTimeout (/.../index.js:83:13)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

`index.js`:

```javascript
const osc = require('osc');

var udpPort = new osc.UDPPort({
    // This is the port we're listening on.
    localAddress: "127.0.0.1",
    localPort: 57121,

    // This is where sclang is listening for OSC messages.
    remoteAddress: "127.0.0.1",
    remotePort: 57120,
    metadata: true
});

// Open the socket.
udpPort.open();

udpPort.on("error", function (error) {
    console.log("Error: ", error.message);
});

// Every second, send an OSC message to SuperCollider
setInterval(function() {

    var msg = {
      address: "/carrier/freq",
      args: [
          {
              type: "f",
              value: 440.4
          },
          {
              type: "[ff]",
              value: [42.0, 47.0]
          }
      ]
    }
    console.log("Sending message", msg.address, msg.args, "to", udpPort.options.remoteAddress + ":" + udpPort.options.remotePort);
    udpPort.send(msg);

}, 1000);
```

**Comment by colinbdclark** [comment]
Thanks for the report, @jarmitage. You don't say what environment you're running in. It looks like Node.js, but which version?

It's probably not related, but also shouldn't you be [waiting for the ready event](https://github.com/colinbdclark/osc.js#sending-osc-messages) before trying to send messages on your Port?

**Comment by jarmitage** [comment]
Hello, I'm new to this lib so quite likely I'm doing something wrong. I'm in node v.8.9.1.

If I change `index.js` to:

```javascript
const osc = require('osc');

var udpPort = new osc.UDPPort({
    // This is the port we're listening on.
    localAddress: "127.0.0.1",
    localPort: 57121,

    // This is where sclang is listening for OSC messages.
    remoteAddress: "127.0.0.1",
    remotePort: 57120,
    metadata: true
});

// Open the socket.
udpPort.open();

udpPort.on("error", function (error) {
    console.log("Error: ", error.message);
});

udpPort.on("ready", function () {
  console.log("ready");
  udpPort.send({
      address: "/carrier/frequency",
      args: [
          {
              type: "[ff]",
              value: [0.0,0.0]
          }
      ]
  });
});
```

I get :
```javascript
ready
Error:  Cannot read property 'writer' of undefined
/.../node_modules/osc/src/osc.js:119
                new Buffer(obj.buffer ? obj : new Uint8Array(obj));
                               ^

TypeError: Cannot read property 'buffer' of undefined
    at Object.osc.nativeBuffer (/.../node_modules/osc/src/osc.js:119:32)
    at osc.UDPPort.p.send (/.../node_modules/osc/src/osc-transports.js:55:23)
    at osc.UDPPort.<anonymous> (/.../index.js:48:11)
    at emitNone (events.js:106:13)
    at osc.UDPPort.emit (events.js:208:7)
    at osc.UDPPort.p.listen (/.../node_modules/osc/src/platforms/osc-node.js:203:14)
    at emitOne (events.js:116:13)
    at osc.UDPPort.emit (events.js:211:7)
    at Socket.onBound (/.../node_modules/osc/src/platforms/osc-node.js:179:18)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by colinbdclark** [comment]
Thanks for the extra details. Strange indeed! I'll take a look and see what might be the cause. Can you confirm that sending a non-array value, like just one float, works ok for you? Is it just array typed arguments?

**Comment by jarmitage** [comment]
Thank you very much for your quick response and for having a look! 

Non-array values work just fine - as a workaround for now I guess I can make a list of args with single float values?

I just realised I'm also getting this warning when using `port.on("ready"..)`:

`(node:98692) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by colinbdclark** [comment]
Thanks again for the report, @jarmitage. This has turned out to be hugely helpful. After a bit of triaging, it seems you've uncovered a long-standing issue in osc.js where writing array-typed arguments isn't properly handled. Wow!

You definitely don't need to downgrade your version of Node—8.x is the new LTS version and is totally supported.

The MaxListenersExceededWarning you're receiving is quite interesting, however. Are you seeing it with exactly the same code as you have [provided above](https://github.com/colinbdclark/osc.js/issues/102#issuecomment-348602732)? Or do you, by chance, have the ready listener being defined within your [previous example's](https://github.com/colinbdclark/osc.js/issues/102#issue-278579184) <code>setInterval</code> callback? If the latter, you're probably registering a new ready listener every second, so that might be the cause?

**Comment by jarmitage** [comment]
Well, glad to help, hope it's not too difficult to fix.

I haven't seen the `MaxListenersExceededWarning` error again so I wouldn't worry about it - I think you're probably right there.

**Comment by turbo5** [comment]
Actually I also just started to have this error recently, MaxListenersExceededWarning.
And the ready event stopped firing as well. Needs further investigation from my side too, but it seems it might really be a bug what has to be solved.

**Comment by colinbdclark** [comment]
Hi @turbo5, do you have any example code that illustrates the issue you're experiencing? Thanks!

**Comment by jarmitage** [comment]
Hi @colinbdclark, just wondering if you'd done any digging on this issue? I'm potentially jumping back to my project that uses `osc.js`

**Comment by colinbdclark** [comment]
Hey @jarmitage, sorry for the delay. I was able to put together a failing test case, and can confirm that it's an issue in the internals of osc.js related to writing array-typed arguments (reading is fine). I've been traveling for the past week and half, and haven't had a chance to implement a fix. I hate to keep you waiting, but it's likely that I'll have to tackle this one over the holidays.

Any chance you can get away with sending multiple arguments instead of one array-typed argument  in your project as a temporary workaround?

**Comment by jarmitage** [comment]
Hi @colinbdclark, no worries the workaround is still fine! Happy holidays 😄

**Comment by colinbdclark** [comment]
Hi again @jarmitage. Having finally found a quiet Saturday to work on osc.js, I took a closer look at your issue, comparing osc.js' actual implementation with its documentation. It seems like the issue was just a mistake in the example code in <code>README.md</code>; array-typed arguments do indeed seem to work correctly (which is a relief, since the tests were all passing). I'm feeling a bit sheepish for not having caught this for you sooner.

Can you try this message format instead and confirm that it does what it should for you?

    {
        address: "/float/andArray",
        args: [
            {
                type: "f",
                value: 440.4
            },
            // Note that array args are structured as, well, an array
            // that contains ordinary osc.js arg objects.
            [
                {
                    type: "f",
                    value: 42.0
                },
                {
                    type: "f",
                    value: 47.0
                }
            ]
        ]
    }

Apologies again for the confusion and the long delay in addressing this, but hopefully it actually does do what you want! :)

**Comment by jarmitage** [comment]
Better late than never! I'm not sure when I'll get to try this but I'll assume you're correct and let you know if I have any problems.
