### ISSUE TITLE
Can not send a message with arguments

### ISSUE THREAD

**Issue by alesandar** [colinbdclark/osc.js#104]
Sending a message with arguments gives me an error. I have tried passing a single argument as a string or integer, and multiple arguments as arrays or objects, but I always get the following error:

```
TypeError: Cannot read property 'writer' of undefined
    at Object.osc.writeArgument (./node_modules/osc/src/osc.js:711:46)
    at Object.osc.collectArguments (./node_modules/osc/src/osc.js:741:34)
    at Object.osc.collectMessageParts (./node_modules/osc/src/osc.js:794:20)
    at Object.osc.writeMessage (./node_modules/osc/src/osc.js:812:33)
    at Object.osc.writePacket (./node_modules/osc/src/osc.js:934:24)
    at osc.UDPPort.p.encodeOSC (./node_modules/osc/src/osc-transports.js:68:27)
    at osc.UDPPort.p.send (./node_modules/osc/src/osc-transports.js:54:28)
    at Object.send (./osc.js:27:7)
    at Object.<anonymous> (./app.js:85:5)
    at Module._compile (module.js:660:30)
```

I am trying to change the BPM in Renoise by running something like that:

```
  udp.send({
    address: "/renoise/song/bpm"
    args: 100
  }, "127.0.0.1", 9129);
```

**Messages that does not require arguments, such as "/renoise/transport/start" and "/renoise/transport/stop" work out-of-the-box.**

**Comment by jean-emmanuel** [comment]
Did you try to wrap your argument in an array ? Also, there is a comma 
missing at the end of line 2 (`|address: "/renoise/song/bpm"|`).

Le 23/01/2018 à 14:07, Alesandar Metodiev a écrit :

**Comment by colinbdclark** [comment]
Hi @alesandar,

Yup, @jean-emmanuel is right; with the current osc.js API, you need to always wrap your arguments in an array, even if there is only one. So this should work:

    udp.send({
        address: "/renoise/song/bpm",
        args: [100]
    }, "127.0.0.1", 9129);

The error message we're throwing in the case where arguments aren't specified in the correct format is unhelpful, so that's something I'll look to improve with better validation in future releases. This is filed under #41.

**Comment by alesandar** [comment]
@colinbdclark, I've already tried wrapping in array, even for a single argument. Still getting the same error. @jean-emmanuel, the missing comma was a typo when I formatted the code here. Thanks to both of you for the fast replies.

**Comment by colinbdclark** [comment]
Hi @alesandar,

Can you provide a full example of the code so that I can try it out?

Thanks!

**Comment by alesandar** [comment]
Yeah, sure. Hope it's simple enough.

filename: osc.js
```
const osc = require("osc")

const udp = new osc.UDPPort({
  localAddress: "0.0.0.0",
  localPort: 57121,
  metadata: true
})

udp.open();

udp.on("ready", function () {
  console.log('UDP is ready')
});

function send(address, args){
  udp.send({
      address: "/renoise/song/bpm",
      args: [100]
  }, "127.0.0.1", 9129);
}

module.exports.send = send
```

filename: app.js
```
const osc = require('./osc.js')
osc.send();
```

**Comment by colinbdclark** [comment]
Thanks @alesandar, this helps a lot.

Your issue is that you're not specifying the necessary type information for your arguments. Open Sound Control is a strongly-typed protocol, and while osc.js offers a somewhat dodgy optional type inference system, you are not using it. When you create your <code>UDPPort</code>, you're setting the <code>metadata</code> option to <code>true</code>, which means that you need to provide the necessary type information yourself. When you call send, you're passing a primitive number without any associated type information. Is it a float? An int? Who knows? :) 

The [osc.js documentation](https://github.com/colinbdclark/osc.js#sample-code-2) provides examples of what your message payload needs to look like.

    udp.send({
        address: "/renoise/song/bpm",
        args: [{
            type: "f",
            value: 100
        ]
    }, "127.0.0.1", 9129);


Your code will probably also work if you construct your UDPPort with <code>metadata: false</code>, though I don't recommend doing so. Better to be explicit about type information when interfacing with a typed protocol where possible.

**Comment by alesandar** [comment]
@colinbdclark, thanks a lot, man! `metadata: false` has resolved my problem!
Thanks for the awesome library. Closing the issue.

**Comment by alesandar** [comment]
By the way, it also works in the explicit way. You've missed a closing curly brace.
```
udp.send({
    address: "/renoise/song/bpm",
    args: [{
        type: "f",
        value: 300
    }]
}, "127.0.0.1", 9129);
```
This way it works. Hope it will be useful for someone.

**Comment by colinbdclark** [comment]
Thanks, I fixed it while you were typing up your post, too. 

Just to be really clear, I strongly recommend using the explicit form, rather than  <code>metadata: false</code>. You will find that some OSC clients will not work unless you explicitly specify the type of your arguments. In the case of song BPM in Renoise, which can take fractional values, you should be fine, but others may require (for example) int-typed arguments which simply can't be inferred in JavaScript, and thus can't be sent without specifying the type metadata explicitly.

Glad I could help and good luck with your project!
