### ISSUE TITLE
TCPSocketPort "error" is called when "close" should be called instead

### ISSUE THREAD

**Issue by jean-emmanuel** [colinbdclark/osc.js#121]
https://github.com/colinbdclark/osc.js/blob/547e361c2a7a9be3ce3adae21f3dbfca62cb3583/src/platforms/osc-node.js#L295

According to https://nodejs.org/api/net.html#net_event_close_1:
> The argument hadError is a boolean which says if the socket was closed due to a transmission error.

TCPSocketPort should not emit "error" when the socket emits "close" as it might prevent from catching the the actual closing event.

**Comment by colinbdclark** [comment]
Thanks so much, @jean-emmanuel!

So if I am reading you right, we should—in the case of <code>err</code> being <code>true</code> here—actually emit both the error and close events? In other words, to remove the <code>else</code> block from this function so that it always emits the close event?

Or is it a semantic issue, and the error event should never be fired as the result of a <code>osc.TCPPort</code> being closed due to a transmission error?

**Comment by jean-emmanuel** [comment]
You're welcome !

It seems the socket's "error" events fires before the related "close" event, I think the close event should be emitted as is, with the boolean error indicator. 

https://nodejs.org/api/net.html#net_event_error_1
> Emitted when an error occurs. The 'close' event will be called directly following this event.

**Comment by colinbdclark** [comment]
Ok, that makes sense to me. I wonder if there are other issues like this in the other transports?

I'll try to make a fix early next week, or I'm happy to look at a PR if you have time. No worries either way, thanks for finding the issue!

**Comment by jean-emmanuel** [comment]
I just proposed a PR. I'm only using udp and tcp in [open-stage-control](https://github.com/jean-emmanuel/open-stage-control), I'll keep you up to date if I find any other issue.

**Comment by colinbdclark** [comment]
Thanks, @jean-emmanuel. I merged your fix and cut a 2.2.2 release. I really appreciate your help with this!

**Comment by jean-emmanuel** [comment]
Thank you :)

**Comment by colinbdclark** [comment]
Fixed in 2.2.2.
