### ISSUE TITLE
"Module parse failed: 'return' outside function" error

### ISSUE THREAD

**Issue by maeganjwilson** [colinbdclark/osc.js#143]
I'm working with Vue and trying to add OSC into my app. When I try to build the app, this is the error I receive:

```
Failed to compile

./node_modules/osc/src/platforms/osc-node-serialport.js 21:4
Module parse failed: 'return' outside of function (21:4)
You may need an appropriate loader to handle this file type.
|     };
| 
>     return;
| }
| 
```

I'm not sure if this is an issue with the file or if this is a web pack type issue

**Comment by colinbdclark** [comment]
Hi @maeganjwilson, sorry to hear it's not working for you. This sounds like a WebPack issue. From your error message, it's trying to compile a Node.js modules for a browser-based project, which won't work very well. I'm not a WebPack user myself, so I've never tried it with osc.js before, but I know others have successfully used it. There is a comment about it on issue #87 that may be helpful. Let me know how it goes!

**Comment by colinbdclark** [comment]
There is a pre-compiled, web-ready version of osc.js in the <code>dist/</code> directory, called <code>osc-browser.js</code>—hopefully this can easily be made to work with WebPack?

**Comment by colinbdclark** [comment]
This may also help: https://github.com/colinbdclark/osc.js/issues/86#issuecomment-357071342

**Comment by jean-emmanuel** [comment]
Well actually having a return statement at top level (ie. outside function) is not valid in ES6 js, although Node accepts it. The error is most likely thrown by the Babel Transpiler which can be told to ignore this rule (https://babeljs.io/docs/en/babel-parser#options, see `allowReturnOutsideFunction`), 

See also this (old) thread on babel's repository: https://github.com/babel/babel/issues/1298

If I were to use the browser version of osc.js, I'd be inclined to transpile it from sources too, however this is not trivial due to the module's structure and [build process](https://github.com/colinbdclark/osc.js/blob/master/Gruntfile.js), so you might want to write `require('osc/dis/osc-browser.js')` instead of `require('osc')` (which only works in node).

**Comment by maeganjwilson** [comment]
I'm trying to run this in a Vue based Electron app originally started with Vue CLI 3. I used what @jean-emmanuel suggested with the require statement, and looks like I don't get the error since I'm pointing directly at the pre-compiled version.

**Comment by colinbdclark** [comment]
@maeganjwilson I'm glad to hear that @jean-emmanuel's suggestion worked well for you. I'll update the documentation to reflect this.

And @jean-emmanuel, thanks for pointing out the return-outside-of-function issue. I will refactor the code to be a little less of a hack. I appreciate the help.

**Comment by colinbdclark** [comment]
osc.js 2.3.1 contains the updated instructions on how to use it with WebPack, and improved factoring of the conditional loading of serial port support. I'll close this issue now, and feel free to file any further issues as needed. Thanks again for your help!
