### ISSUE TITLE
Error: Can't infer OSC argument type for value: [object Object]

### ISSUE THREAD

**Issue by gonogo** [colinbdclark/osc.js#17]
Hi, Whenever I run the following code, I receive the message `Error: Can't infer OSC argument type for value: [object Object]`. Is this a bug? I've followed the example taken from the documentation and can't make this work. The code is as follows. Am I missing something obvious or is this a bug? Thanks

    var osc = require('osc');
    var udpPort = new osc.UDPPort({
        localAddress: "127.0.0.1",
        localPort: 57111
    });
    udpPort.open();
    udpPort.send({
        address: "/sl/1/down",
        args: [
            {
                type: "f", // OSC type tag string
                value: 444.4
            }
        ]
        }, "127.0.0.1", 9951
    );

**Comment by colinbdclark** [comment]
Hi @gonogo, thanks for the report.

The issue is an error of omission in the documentation. Currently, osc.js can read and write two different forms of message arguments: ones that are annotated with type metadata, and ones in which the types are inferred. By default, osc.js will attempt to do type inference. You can change this behaviour by setting the <code>metadata</code> option to <code>true</code> when you instantiate your <code>OSCPort</code>:

    var udpPort = new osc.UDPPort({
        localAddress: "127.0.0.1",
        localPort: 57111,
        metadata: true
    });

    udpPort.send({
        address: "/sl/1/down",
        args: [
            {
                type: "f", // OSC type tag string
                value: 444.4
            }
        ]
    }, "127.0.0.1", 9951);

But in my experience, specifying explicit types is rarely necessary. Unless you're sending to an OSC receiver that, for example, explicitly requires integers (in JavaScript, all numbers are floating point), you can send typeless messages and osc.js will infer argument types for you. Like this:

    udpPort.send({
        address: "/sl/1/down",
        args: [444.4]
    }, "127.0.0.1", 9951);

All that said, I don't see why osc.js needs to be so specifically modal in its operation when it comes to writing messages. I'm looking into the possibility of supporting mixed messages (i.e. some typed and some not typed). But this will introduce an asymmetry in the read and write APIs, since of course you'll still need to manually specify the <code>metadata</code> option when reading OSC messages if the type metadata is important to you. I'll see what I can come up with.

In the meantime, the fix for you is to either specify the <code>metadata</code> flag or omit type metadata in your messages, as many of the examples show. I'll update [the documentation](https://github.com/colinbdclark/osc.js#argument-objects-with-type-metadata) to make this clear.

**Comment by colinbdclark** [comment]
I've just addressed this issue by expanding the inference logic to recognize typed arguments. I still recommend that users who are using typed arguments supply the <code>metadata: true</code> flag when constructing an <code>OSCPort</code> instance, in order to avoid confusion related to messages being sent in one format and received in another.

I've released version 1.1.1 with this fix in it. @gonogo, let me know if this addresses your problem and please feel free to close the issue if so.

Thanks again for pointing this out!

**Comment by gonogo** [comment]
Hi @colinbdclark,

Thanks for looking into this and taking the time to fix it. I updated with the new version and it's working fine now. Nice job, thanks!
