### ISSUE TITLE
osc.timeTag() not working

### ISSUE THREAD

**Issue by RuolunWeng** [colinbdclark/osc.js#170]
Hello,

I'm new to this package, just want to implement Timetag in OSC bundle. But when I test the example code in Readme, TimeTag is not scheduled, it's been sent directly.

Thanks for your help!

==================
oscPort.send({
        timeTag: osc.timeTag(60), // Schedules this bundle 60 seconds from now.
        packets: [
            {
                address: "/carrier/frequency",
                args: [
                    {
                        type: "f",
                        value: 440
                    }
                ]
            },
            {
                address: "/carrier/amplitude",
                args: [
                    {
                        type: "f",
                        value: 0.5
                    }
                ]
            }
        ]
    });

**Comment by colinbdclark** [comment]
Hi @RuolunWeng, sorry to hear you're having difficulty with your project. What you describe seems to be the expected behaviour, and is consistent with the [Open Sound Control specification](http://opensoundcontrol.org/node/3/#timetags), which says that it's the receivers job to invoke OSC messages in accordance with the time tag it received. osc.js, by design, doesn't delay or sequence messages that you send. In other words, <code>osc.send()</code> will always send your message immediately; the receiver should determine when and how to invoke the message.

**Comment by RuolunWeng** [comment]
Hi @colinbdclark, thank you for your quick reply..
So like I am new to this domain, do you have some example code on the client side to manipulate the timetag?

**Comment by colinbdclark** [comment]
I'm sorry, I don't. It would depend on where you're sending the bundle to, what language your receiver is written in, and what it actually does with the messages within the bundle. The OSC spec outlines what kind of algorithm you should implement. In general you're going to compare the time tag of the incoming bundle to the current time. You'll need to determine your own tolerances for latency, but generally if the time tag is in the past or very close to the current moment, you'll act on it immediately, otherwise you might use (if your receiver is written in JavaScript) <code>setTimeout()</code> or a more accurate scheduler of your choosing to defer operation on the bundle until later.

**Comment by RuolunWeng** [comment]
I’m using Javascript in nodeJS for the receiver... 
I will try to find a scheduler for that like you said. Thanks again for your help！
