### ISSUE TITLE
OSC.js to Sonic Pi

### ISSUE THREAD

**Issue by quintendewilde** [colinbdclark/osc.js#174]
I see there are issue with sending messages to sonic pi.

Sonic pi internally ads the local host to the incoming messages and osc.js does this to. 
The result is that the local host comes into the message. 

<img width="410" alt="Screenshot 2020-09-26 at 14 53 20" src="https://user-images.githubusercontent.com/6031569/94365666-0e1fda00-00d3-11eb-84bc-381e99281cb4.png">

**Comment by colinbdclark** [comment]
Hi @quintendewilde, I'm sorry, I don't understand your issue here. osc.j does not "add the localhost" to message (though I'm not sure quite what that means). It sends precisely the message you provide it with, to the address and port you specify.

Rather, this looks to me like Sonic Pi has a particular format for logging incoming OSC messages, which shows you the address and port on which it was received, for convenience. I'm not a Sonic Pi user, but it sounds like you will need to [use get and sync](https://github.com/sonic-pi-net/sonic-pi/blob/main/etc/doc/tutorial/12.1-Receiving-OSC.md) to actually read values out of the incoming OSC messages.

I'm going to go ahead and close this issue, since it doesn't seem to have anything to do with osc.js, and I am unable to act upon it any way. Feel free to reopen if you think there is a specific bug in osc.js, and can provide a simplified test case that will help me track down the issue.

Good luck with your project!
