### ISSUE TITLE
Uncaught ReferenceError: OSC is not defined 

### ISSUE THREAD

**Issue by dblanchemain** [colinbdclark/osc.js#176]
<!DOCTYPE html>
<html>
    <head>
        <title>osc.js Web Sockets</title>
        <meta charset="UTF-8" />
        <script t type="text/javascript"  src="osc.js"></script>      
    </head>
    <body>
    <button id="send"> Test</button>
		<script type="text/javascript">

		const osc1 = new OSC();
		osc1.open({host:localhost, port:3819});
  		document.getElementById('send').addEventListener('click', () => {
   	var message = new OSC.Message('/strip/list');
    	osc1.send(message);
  });
</script> 

    </body>
</html>
I am unable to send an osc message to Ardour (DAW localhost port: 3819). I still have an error message: with the OSC object :  OSC is not defined (with chrome)

**Comment by colinbdclark** [comment]
Hi @dblanchemain, sorry to hear about your difficulty. There seems to be some confusion; it looks like you’re using the API of a different OSC library. Did you mean to file this ticket somewhere else? Otherwise, this project’s [README](https://github.com/colinbdclark/osc.js/blob/master/README.md) provides full documentation on how to use it. 

Good luck!

**Comment by colinbdclark** [comment]
Closing due to a lack of response. Feel free to re-open if you encounter any issues with osc.js itself.
