### ISSUE TITLE
Object as OSC Msg Best practice in OSCJS Lib

### ISSUE THREAD

**Issue by KonVas** [colinbdclark/osc.js#177]
Hello,

I am generating my OSC data msgs as an object in my code, but when I am trying to send it over in SuperCollider (irrelevant) it crushes my node app. To fix this I am stringifying all the object and sending over succesfully. Is this the only way to send an object as OSC msg or there is some other elegant way.

```
obj  = {
x:0.1,
y:0.2,
z:0.3
}

osc.udpPort.send({
                address: "/path/",
                args: [
                    {
                        type: 's',
                        value: JSON.stringify(obj) //should this be okay or there is a better way to deal with
                    }
                ]
            })
```

**Comment by colinbdclark** [comment]
Hi @KonVas, that sounds like an interesting project. Yes, the OSC spec has no object type so I think your approach is probably the best; stringify your object as JSON, send it via OSC, and then parse it back into an object using SuperCollider's JSON Quark or something similar. 

I guess the alternative would be to represent your object as a series of address paths, and write some custom code to create bundles of messages for each property, and the reverse code on the SuperCollider side of things, but that's probably less efficient. Some of it might be depend on whether you want to support changes to portions of the object, rather than the whole thing.

If it were me, I'd just do what you're doing. 👍

**Comment by KonVas** [comment]
That saves me from some doubts regarding efficiency. I used the separate way of sending an OSC bundle with different messages indeed but it makes the code big for no reason, instead, I like the idea of encapsulating into a single object and send it over then let the respondent to deal with it. In SC then I can turn this into a dictionary using 'msg.asString.parseYAML' it makes it very handy. Yeah, this might be odd, at least for me, while JSON.stringify's task is turning this to a string, SC parses it as a Symbol and thus it needs to be converted to a String. I thought that might be something with the lib but I speculate it's some OSC-networking compliant issue. Thanks for the input.
