### ISSUE TITLE
sending large json as stringfied string gets cropped

### ISSUE THREAD

**Issue by UnivateBV** [colinbdclark/osc.js#188]
Hello,
i have a interesting error. I am sending two large stringified json objects as string via osc. The larger one works fine but the smaller one with around 2500 characters gots cropped at the end. Any ideas where this can come from?

**Comment by UnivateBV** [comment]
Hmmm the problem is that this data is confidential. What i can do is i can share my sending function.
`let m = {};
        m[prefix] = data;
        let s = JSON.stringify(m);
        oscSender.send({
            address: endpoint,
            args: [
                {
                    type: "s",
                    value: s
                }
            ]
        });`

and the data object looks like this
`[{name:"john"},{name:"doe"},{name:"foo"}]`

**Comment by UnivateBV** [comment]
and the osc sender is this
``const udpPort = new osc.UDPPort({
    localAddress: "0.0.0.0",//127.0.0.1 for no multicast
    localPort: 7001,
    remoteAddress: "127.0.0.1", // local
    remotePort: 7000, //7000 the port to send to
    metadata: true//true
});
// Open the socket.
udpPort.open();

**Comment by colinbdclark** [comment]
A simplified test case need not reveal confidential data—and it might help you track down the issue yourself. If you can, put together a little standalone application using non-confidential test data and code that I can run in Node.js, which illustrates the problem so that I can take a look.

If this is a for-profit project you're asking for help with, I'd just like to remind you about the asymmetry of the relationship here. I'm happy to help, but remember that I develop, share, and maintain this library in my spare time. This means that when you're asking for help, you're getting paid to ask; when I respond, I'm doing so as a gift to you. The more you can help me to more efficiently help you, the fairer this relationship is. Thanks so much!

**Comment by UnivateBV** [comment]
This is not a commercial case by now. It is a proof of concept, which is failing. So i will try to solve it by myself or test it with another osc implementation thanks. Otherwise i can ask my boss if we can spend some money on this. I will keep you updated

**Comment by colinbdclark** [comment]
Just to be clear, @UnivateBV, I'm not asking about money (nor would I accept it if you or your boss offered). I'm asking for a test case that illustrates the problem you're describing, which I can run on my machine, so that I can help you troubleshoot the issue. That's not too much to ask from a volunteer, is it?

**Comment by colinbdclark** [comment]
Indeed, you could even add some new data based on your issue to the library's own unit tests and see if you can reproduce the failure you're experiencing—which would be extremely helpful, and only require a few lines of code.

**Comment by colinbdclark** [comment]
No response in three weeks, so I'm assuming this wasn't a bug in the osc.js library directly. Please feel free to reopen if there is a test case or simplified example I can use to triage the issue.
