### ISSUE TITLE
Issues related to new version of serialport?

### ISSUE THREAD

**Issue by thomasfredericks** [colinbdclark/osc.js#199]
Thanks for the great library! I have encountered an issue with the version of serialport.
When I install with the following dependencies, npm tries to install serialport 9.2.4 but then the package cannot be found:
```
    "dependencies": {
        "osc": "2.4.2",
	 "express": "4.17.1",
        "ws": "7.5.3"
    }
```
<img width="674" alt="image" src="https://user-images.githubusercontent.com/2685516/197874521-07a13822-bdb5-4ae2-9571-44c160404f57.png">

But if I change the dependencies to the following everything runs and installs fine:
```
    "dependencies": {
	"serialport":"9.2.8",
        "osc": "2.4.2",
		 "express": "4.17.1",
        "ws": "7.5.3"
    }
```
<img width="674" alt="image" src="https://user-images.githubusercontent.com/2685516/197874915-ef67ca86-2bed-4f39-ae5a-4595c6432511.png">

Maybe the serialport dependencie of OSC.js should be updated to "9.2.8"?
```
    "optionalDependencies": {
        "serialport": "9.2.0"
    },
```

Also, are you planning to update to serialport version 10?

Thank you!

**Comment by colinbdclark** [comment]
Hi @thomasfredericks, thanks for the report and sorry to hear it wasn't working for you. Just to confirm, if you update the version of ```serialport``` in ```optionalDependencies``` instead of moving it to a hard dependency as you did, does your program also work?

I haven't tracked updates to the serialport library, but version 10 may involve breaking changes so it'll involve additional testing. I'd be happy if you have time to take a look and to hear if you encounter any major issues with it. Thanks!

**Comment by thomasfredericks** [comment]
Hi, I will test the `optionalDependencies ` but YES, version 10 does involve major breaking changes. Basically,  SerialPort becomes a subclass of serialport...
