### ISSUE TITLE
Can not compile for iojs 2.3.1

### ISSUE THREAD

**Issue by 0x80** [colinbdclark/osc.js#21]
I'm getting errors like this

```
npm install osc --save
|
> utf-8-validate@1.0.1 install /Users/me/Development/myproject/node_modules/osc/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call,
      expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/me/.node-gyp/2.3.1/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
```

**Comment by colinbdclark** [comment]
Hi @0x80, thanks for pointing out the issue. I'll take a closer look when I get some free time. I don't currently use io.js, so it may take a bit of time to get it all set up and running.

In the meantime, it looks like this error is due to API changes in the version of v8 that ships with io.js, which the nan library doesn't support. osc.js doesn't depend directly on this library, and it looks like the only package that osc.js depends on that could be affected is the serialport package. Currently, I'm linking to an older version (1.5.0), but there is a newer version available.

If you've got a quick second to experiment, can you try updating the version of serialport in osc.js' <code>package.json</code> to 1.7.4 and see if that fixes the issue?

**Comment by 0x80** [comment]
Hi, I don't have time right now to experiment, but I can confirm that serialosc 1.7.4 is compatible with iojs 2.3.1 since I'm already using that in this project. However I'm working with the Electron shell and for this serialosc-electron was created as a workaround because the official version has problems with node-gyp...

**Comment by colinbdclark** [comment]
Just so I follow, when you said serialosc and serialosc-electron, did you mean **serialport**?

**Comment by 0x80** [comment]
Yes I immediately edited my message when I noticed it but you were too fast ;)

**Comment by 0x80** [comment]
I just noticed how similar our avatars are :)

**Comment by colinbdclark** [comment]
lol, no worries! I read up on the situation [in the node-serialport issue tracker](https://github.com/voodootikigod/node-serialport/issues/538) and it looks like a sticky one. I'll update osc,.js to use the latest 1.7.4 version. It should be possible for you, if needed, to make a temporary fork of it to use the serialport-electron fork until someone sorts the whole toolchain out.

Thanks again for pointing out the issue! I am looking forward to io and Node merging again one of these days!

**Comment by colinbdclark** [comment]
I have updated osc.js' dependencies to the latest versions, which should address this issue. I'll leave this issue open until an io.js user out there can test and confirm for me.

**Comment by 0x80** [comment]
I just did a quick npm install. Seems to be fine! :+1:

**Comment by colinbdclark** [comment]
Thanks, hugely appreciated!
