### ISSUE TITLE
readBlob returns full bundle to not differentiating ArrayBuffer vs Buffer

### ISSUE THREAD

**Issue by fde31** [colinbdclark/osc.js#29]
I was dealing with packets and nested bundles and noticed that the nested bundle is always equal the top level buffer. First I thought it's due to weird messages coming in but then came across a pretty nasty bug.

In https://github.com/colinbdclark/osc.js/blob/master/src/osc.js#L355 a new UInt8Array is created using the incoming buffer. On first glance this seems fine when referring to the TypedArray constructor as documented here (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Syntax)

> new TypedArray(buffer [, byteOffset [, length]]);
>
> When called with a buffer, and optionally a byteOffset and a length argument, a new typed array view is created that views the specified ArrayBuffer. The byteOffset and length parameters specify the memory range that will be exposed by the typed array view.  If both are omitted, all of buffer is viewed; if only length is omitted, the remainder of buffer is viewed.

However this fails in a Node.js environment as the input is a Node Buffer instance and not an ArrayBuffer instance. Due to that the TypedArray constructor treats it as an Array and ignores the offset and length parameters.

I committed a simple fix to my fork (see https://github.com/fde31/osc.js/commit/961da012a3aea2b1f8dcef9a78abaa4dda9addae) but maybe there is a more consistent way to fix this? On a first glimpse it seems like there might be 2-3 other situations where this might be a problem.

Any thoughts?

**Comment by colinbdclark** [comment]
Hi @fde31, thanks for filing the bug. Can you provide any kind of test case or example so that I can take a look at the issue?

**Comment by fde31** [comment]
Sure @colinbdclark, will make a simple test to reproduce in the next days.

**Comment by colinbdclark** [comment]
Hugely appreciated! Thanks again for reporting this issue.

**Comment by colinbdclark** [comment]
I have a [working branch](https://github.com/colinbdclark/osc.js/commit/8bbdd4fcb791f7dacd422413f6da6ecf07bc19d8) that fixes this issue. However, it is not API compatible with osc.js 1.x, since all the low-level osc.* functions now operate solely on TypedArrays and no longer support Node.js Buffers.

However, the higher-level transports now take care of ensuring that we're using the correct type of buffer for the platform; on Node.js, all the transports will convert from osc.js' <code>Uint8Array</code>s to <code>Buffer</code> objects.

I'm assuming that there are probably few if any users who are using the low-level Node.js functions directly, so this likely will be a seamless upgrade for everyone, but I'd like to let this sit for a few days in case anyone has concerns. This fix, along with (potentially) the gh-32 fix, will comprise the osc.js 2.0.0 release.

**Comment by colinbdclark** [comment]
Fixed in osc.js v2.0.0.
