### ISSUE TITLE
Handling misaligned OSC messages/bundles

### ISSUE THREAD

**Issue by tambien** [colinbdclark/osc.js#30]
Great library! it's been very useful for me so far. 

I have a question about handling misaligned messages on Serial/UDP streams. Right now it [throws an error](https://github.com/colinbdclark/osc.js/blob/master/src/osc.js#L904-L905) when I decode a packet that doesn't start with a bundle or message. The difficulty i'm having is when trying to connect to a serial device which is streaming packets, it's very rare that I connect at the precise moment when the stream is at the beginning of a message or bundle, so i often get this unhandled error which exits my application. I'd prefer instead to just drop that packet and continue parsing until the next full packet is available. I think this error would also come up if the stream dropped some bytes at some point. 

I'm wondering how/where you would recommend catching these errors so that my application can continue parsing the stream without exiting. 

As a temporary fix, I added a `try/catch` block on [these lines](https://github.com/colinbdclark/osc.js/blob/master/src/osc-transports.js#L63-L66) and simply log the error and continue decoding. Maybe it'd be useful to emit an "error" event in this case?

**Comment by colinbdclark** [comment]
Hey Yotam, I'm really glad to hear that osc.js is useful for you! Your issue raises a really good point, and one that I admit I haven't thought clearly about until now; it's definitely a bug in osc.js.

I think your suggestion is a good one. The lower-level osc.js read and write functions should probably continue to throw errors, and the higher-level Transports (which are event emitters) should try/catch those lower-level functions and emit error events instead of exploding. I can implement this in the next release of osc.js, and I'm always happy for pull requests if you have the time.

One thing I'm curious about: you mention that you've experienced this over UDP as well as serial? I can totally understand how you might well start listening to a stream midway through a large OSC packet while receiving SLIP-framed data over serial (maybe from an Arduino device?), but are there circumstances where you're somehow receiving multiple UDP packets per OSC message? My understanding of the OSC specification is that, when transported over UDP, an OSC packet must fit within a single UDP packet. But perhaps I'm confused.

Thanks again for the bug report. I really appreciate it!

**Comment by tambien** [comment]
I only experienced this issue using the serial layer. i thought this might be an problem over UDP as well since the transmission is not guaranteed, but looking into it a little more, i think you're right that the IP packet(s) will be reassembled in their entirety or be dropped altogether removing the need to handle incomplete messages when using UDP.

**Comment by colinbdclark** [comment]
Thanks for the pull request, @tambien! I've extended it to ensure that we're emitting errors in any case where we're calling the low-level osc.js APIs, and I'll write up some unit tests for it and cut a new release as soon as possible.

**Comment by colinbdclark** [comment]
Hi @PTS93, I'm sorry to hear you're having problems. I don't have enough information to lend a hand as-is. Can you open a new ticket with further details about what you're encountering and with some example code that shows the issue? Which transport are you using? Is there a particular client that is sending the data? Thanks!

**Comment by PTS93** [comment]
Sure! I opened up a new issue here: https://github.com/colinbdclark/osc.js/issues/127
