### ISSUE TITLE
Unable to send a stringified Javascript object with Unicode characters via websocket

### ISSUE THREAD

**Issue by jchavarri** [colinbdclark/osc.js#40]
I have a basic OSC websocket configuration, and I'm trying to send JS Objects between both.

I understand that I need to convert these JS Objects into an OSC compatible type, but even if I use `JSON.stringify()` to convert them, I get also an error due to the way osc.js encodes unicode strings.

Here are the client and server code I'm using, commented for better understanding:

**Client (file `index.html`)**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>osc.js Web Sockets</title>
        <meta charset="UTF-8" />
        <script src="bower_components/osc.js/dist/osc-browser.js"></script>
        <script>
            var port = new osc.WebSocketPort({
                url: "ws://localhost:4001"
            })

            port.on("ready", function() {
                console.log("ready!!!");
                var myObject = {
                    oneProperty: "Murdock’s Fougere",
                    anotherProperty: "a gentleman’s look"
                }
                // port.send({
                //     address: "/subscribe",
                //     args: "Murdock’s Fougere"
                // });
                
                ////// Option 1 - Send it as a JS Object (not possible as it's not an OSC supported type)
                
                // In this case it should show an error message saying it's unable to convert, but I get the following error on the client:
                //
                //      Uncaught TypeError: Cannot read property 'buffer' of undefined
                //          osc.isTypedArrayView @ osc-browser.js:44
                //          osc.nativeBuffer @ osc-browser.js:121
                //          p.send @ osc-browser.js:2865
                //          ...
                port.send({
                    address: "/someAddress",
                    args: [myObject]
                });
                
                ////// Option 2 - Send it as JSON stringified string
                
                // In this case it's the server that crashes:
                //
                //      events.js:141
                //          throw er; // Unhandled 'error' event
                //          ^
                //
                //      SyntaxError: Unexpected token 
                //          at Object.parse (native)
                //          at null.<anonymous> (/Users/.../server/index.js:14:47)
                //          ...
                port.send({
                    address: "/someAddress",
                    args: JSON.stringify(myObject)
                });
            }); 

            port.on("close", function() {
                console.log("Close");
            });

            port.open();
        </script>
    </head>
    <body></body>
</html>
```

**Server (file `index.js`)**
```javascript
var osc = require("osc"),
    WebSocket = require("ws");

var wss = new WebSocket.Server({ port: 4001 });

wss.on("connection", function (socket) {
    console.log("A Web Socket connection has been established!");
    var socketPort = new osc.WebSocketPort({
        socket: socket
    });

    socketPort.on("message", function (oscMsg) {
        console.log("An OSC Message was received!", oscMsg);
        //This is the line that crashes when trying option 2
        console.log("Trying to parse: ", JSON.parse(oscMsg.args[0]));
    });
});
```

**Version**
I am using for both the client and the server the osc.js version of commit [872f4ba](https://github.com/colinbdclark/osc.js/commit/872f4ba09a050038b63a2c05349befa3628d53de), I believe that's the latest one at the moment.

Please let me know if you need further tests or information. Thanks!!

**Comment by jchavarri** [comment]
For now, I found a work around. I solved it by encoding the stringified object before sending, and decoding it on reception:

```javascript
// Before sending (on client)
var encodedObject = unescape(encodeURIComponent(JSON.stringify(myObject)))
// After sending (on server)
var objectReceived = JSON.parse(decodeURIComponent(escape(messageArgs[0])))
```

**Comment by colinbdclark** [comment]
Hi @jchavarri, thanks for the report. In the case of your "Option 1," I agree that osc.js should do a better job of validating message specifications and throwing helpful error messages if they're not in the correct format.

The larger issue, however, is trickier. Unfortunately the [Open Sound Control specification](http://opensoundcontrol.org/spec-1_0) requires that strings must only consist of ASCII characters. If I were to add any other string encoding options, osc.js would no longer be compliant with implementations that expect only ASCII strings. And there's no easy way to extend OSC with your own custom types in an interoperable way.

Your approach of using <code>encodeURIComponent</code> is a pretty reasonable option for addressing this limitation of OSC. It will require both sides of the communication to know about the encoding, and to have a viable URI encoder/decoder (which most languages have). 

Alternatively, you could use a text encoding polyfill for the new [Text Encoding](https://encoding.spec.whatwg.org/) spec, such as [TextEncoderLite](https://github.com/coolaj86/TextEncoderLite) and then send your strings as OSC blobs.

I'll think about what we can do in terms of providing utilities in osc.js for making this easier (perhaps a <code>encodeJSONObject()</code> utility function?), but ultimately it will have to part of an application-level contract, since the OSC specification doesn't provide any standard way to this.

Thanks again for filing this!

**Comment by jchavarri** [comment]
I understand, thanks a lot for the detailed explanation! I now see very clearly how this feature should be part of the application contract, and it certainly seems out of the scope of the library.

Thanks for the hint about the Text Encoding spec, I didn't know about that and it's worth taking a look.

I am closing the issue for now.
