### ISSUE TITLE
Is osc.js supposed to be useable in a standalone web page?

### ISSUE THREAD

**Issue by jkleiser** [colinbdclark/osc.js#53]
Right now I just want to test sending and receiving simple OSC messages at specified ports. Can I do that from a local HTML page, with dist/osc-browser.min.js, without any server at all?

**Comment by colinbdclark** [comment]
Hi @jkleister,

It's not clear from your question what kind of OSC messages are you interested in sending from a web page. In particular, what kind of transport are you trying to communicate over?

With osc.js running within a standard web browser page, you can only send OSC messages via a Web Socket. This will, of course, require a server to establish a connection with. For example, many osc.js users employ a Node.js server to proxy messages between a UDP connection and a Web Socket talking to a browser-based client. There are examples in the [osc.js-examples repository](https://github.com/colinbdclark/osc.js-examples).

Pure web clients aren't capable of making low-level UDP or TCP connections. If you want to do that, and you're willing to limit yourself to Chrome only, you could look at creating a Chrome application. osc.js supports both UDP and serial for Chrome apps.

Otherwise, you'll need some kind of server.

**Comment by jkleiser** [comment]
Thanks. I am now using the osc.js-examples/tree/master/udp-browser, and it works fine.

**Comment by colinbdclark** [comment]
I'm glad to hear it's working for you, that's awesome!
