### ISSUE TITLE
OSC from browser over websocket - not working, no error

### ISSUE THREAD

**Issue by yaxu** [colinbdclark/osc.js#57]
I'm having troubles getting an OSC message from my web browser. I've made the below minimal example, which tries to connect to localhost.

I've tried loading the below page locally (file://) and via a web server running on localhost. I've also tried loading it in both firefox and chrome. No error is thrown and the return value is undefined. Nothing appears on the console. No connection is made according to network sniffer (wireshark), I see the http connection to load the webpage but no web socket. I'm using osc.js 2.0.3. Any tips much appreciated!

````
<!doctype html>
<meta charset="utf-8"/>

<html>
<head>
<script src="osc-browser.js"></script>
</head>
<body>
osc test
    <script>
      var changes = [];
      var oscPort = new osc.WebSocketPort({
            url: "ws://localhost:9160" // URL to your Web Socket server.
      });
      oscPort.on("error", function (error) {
        console.log("An error occurred: ", error.message);
      });
      var rv = oscPort.send({
           address: "/hello",
           args: 0.5
      });
      alert("sent: " + rv);
   </script>
</body>
</html>
````

**Comment by colinbdclark** [comment]
Hi Alex,

Nice to hear from you, and sorry you weren't able to get it working. You posted your client-side code, but I didn't see anything in terms of what you're running on the server in order to serve up the Web Socket connection. Can you give me more background on what you're trying to communicate with on the other side?

As background, Web Sockets involve a client/server architecture: you need a Web Socket-enabled server to go with your client. A lot of osc.js users typically have a Node.js app that hosts the client web page and responds to WS requests from using the [ws](https://github.com/websockets/ws) library and something like [express](https://github.com/expressjs/express). But you could use Python, Java, Ruby, or another language for the server. As far as I know, there's also a Haskell WS server available.

The [osc.js examples repository](https://github.com/colinbdclark/osc.js-examples) has [an example server](https://github.com/colinbdclark/osc.js-examples/blob/master/browser/index.js) that illustrates how this works when you want to relay OSC messages sent over UDP from a "native" client to a web page using Web Sockets.

The reason you didn't see an error in your pasted example is because you didn't <code>open()</code> the socket prior to sending to it. Sounds like there is a bug in osc.js since it doesn't raise an error if you try to send messages on a closed <code>Port</code>. I've filed #58 about this and will fix it soon. Is there also some example code that you derived this from that should be updated to correctly open the Port?

Thanks again for the report, and hopefully this is helpful!

**Comment by yaxu** [comment]
Aha, thanks for the comprehensive response! Clearly I'm too used to sending OSC over UDP which I suppose wouldn't need that step.

I was trying to connect to some Haskell code on the server side, but wasn't seeing the connection attempt so didn't bother making a minimal example of that. In my experience so far the Haskell websocket library works well.

I'll have another go, actually opening the port this time :)
