### ISSUE TITLE
Get IP address of the sender on incoming message

### ISSUE THREAD

**Issue by YohannLYD** [colinbdclark/osc.js#67]
I am looking for a way to get the IP address of a sender on incoming message.
Is it possible to include this information within the incoming message data (and would it make sense ?).

**Comment by colinbdclark** [comment]
Hi @YohannLYD, 

The sender's IP address is available for some transports, but not for others (since, for example, some transports don't use IP networking at all). You don't mention which osc.js transport you're using, and on which platform. But I'm guessing from your question that you're probably using the UDP transport on Node.js.

The third argument to a <code>message</code> [event listener](https://github.com/colinbdclark/osc.js#events) consists of platform-specific information. In the case of a <cod>UDPPort</code> used on Node.js, this will be the <code>rinfo</code> object from the uderlying [Node.js UDP socket message event](https://nodejs.org/api/dgram.html#dgram_event_message).

Does this do what you need it to?

Colin

**Comment by YohannLYD** [comment]
Hi Colin,
That's exactly what I needed to know as I am indeed using UDP on node.js.
Thanks for the quick answer!

Yohann
