### ISSUE TITLE
Howto: make it work with Electron

### ISSUE THREAD

**Issue by jean-emmanuel** [colinbdclark/osc.js#69]
Since `serialport` doesn't work with Electron, here's a hack / workaround for those who actually don't use serial port transport with ocs.js. One just needs to add one dependency, `vmodule` and use it to override the `serialport` module with an empty one before requiring `osc` : 

``` js
var vmodule = require('vmodule')

vmodule('serialport', {}, {global: true})

var osc = require('osc') // This would normally fail in Electron
```

**Comment by colinbdclark** [comment]
Hi @jean-emmanuel, thanks for the workaround!

Support for Electron has been added to osc.js and will be released in the next version; you can track #65 for background information, and try out the [gh-65 branch]( https://github.com/colinbdclark/osc.js/tree/gh-65) to see it in action. The only thing I'm missing now, I think, is the ability to run the osc.js test suite in Electron, which I'm working on now.

When version 2.2.0 of osc.js released, it should work out of the box with Electron, including support for the serial port.

If I remember correctly, you published a fork of osc.js a while ago with Electron support, right? Maybe once the 2.2.0 release is out, you can update the README of your fork to point users to the latest mainline release of osc.js so they don't get confused?

Version 3 of osc.js, for the record, will fully modularize the transports so that users can pick and choose the ones they want in each environment.

**Comment by jean-emmanuel** [comment]
That's awesome, I'll check it out and update the README with pleasure !

By the way, if this is of any relevance, here is the project of mine depending on osc.js : https://github.com/jean-emmanuel/open-stage-control

**Comment by brucelane** [comment]
@jean-emmanuel I would like to use your software in my VJ app (videodrömm)!

**Comment by colinbdclark** [comment]
[osc.js v2.2.0 is now available](https://github.com/colinbdclark/osc.js/releases/tag/2.2.0), with support for Electron-based applications!

**Comment by colinbdclark** [comment]
I'm closing this issue since the workaround it documents is no longer required. Thanks for your help with this issue, @jean-emmanuel. And your Open Stage Control application is awesome!

**Comment by jean-emmanuel** [comment]
Thanks a lot for your work !
I'm updating the mirror's README as asked.
