### ISSUE TITLE
Using osc.js with Electron requires it to be built against Electron's V8, not the default Node.js version

### ISSUE THREAD

**Issue by jean-emmanuel** [colinbdclark/osc.js#78]
As written in serialport's [documentation](https://github.com/EmergingTechnologyAdvisors/node-serialport#electron), [`electron-rebuild`](https://github.com/electron/electron-rebuild) must be run after installing serialport (and osc.js). It might be worth mentioning it in the docs.

**Comment by colinbdclark** [comment]
Hi @jean-emmanuel, good point! The issue, as the documentation says, is that, by default <code>npm install</code> will build serialport against the regular version of Node.js installed on your computer, not the one that is used by Electron.

It's strange, however, that serialport's documentation is so prescriptive regarding the use of electron-rebuild. It's certainly one option available to developers. I'm no expert Electron developer, but it seems to me that it's faster and more reliable to use an <code>.npmrc</code> file to ensure that npm always builds against Electron's V8, rather than Node.js. There's an [example of using an .npmrc file to build an Electron app](https://github.com/colinbdclark/osc.js-examples/blob/master/electron/.npmrc) in the osc.js-examples repository.

Perhaps there are other reasons and benefits for using electron-rebuild that I am unaware of, however.

I'll update the documentation with the various options available to developers. Thanks so much for pointing this out!

**Comment by jean-emmanuel** [comment]
I didn't know the `.npmrc` way, it looks better indeed !
