### ISSUE TITLE
Serverless browser

### ISSUE THREAD

**Issue by sinokgr** [colinbdclark/osc.js#97]
Hi there,
Do you know if there is anyway to do a similar [UE4/TouchOSC](https://www.youtube.com/watch?v=GGGs-n-CKtY) type of interaction with your project without a server? I want to create the GUI for Unreal in html/js but I would like to avoid using a server. 
Thanks

**Comment by colinbdclark** [comment]
Hi @sinokgr, I don't have any experience with Unreal Engine. I'm also not fully clear on what kind of an architecture you're considering—are you hoping to have a separate, browser-based user interface communicating with code running in a separate Unreal application? In that case, you'll invariably need some kind of server. Ordinary web browsers can't directly make UDP or TCP connections to other applications.

Perhaps Unreal Engine has support for operating a Web Sockets server, and then you might be able to have your HTML client connect directly to it? Otherwise, I've read that there are projects like [BLUI](https://github.com/AaronShea/BLUI) that allow you to write HTML UIs within Unreal Engine using Chromium Embedded Framework, and presumably offer some sort of IPC or other way to send messages between them. Beyond that, I unfortunately don't know enough about Unreal to be of much help.

**Comment by sinokgr** [comment]
Many thanks for the quick reply @colinbdclark. Yep, that's what I want to do. Have a GUI in a tablet/phone running a brower-based user interface that will control UE4 using OSC. I was afraid it's not possible, but I wanted to double-check.

So, if I have to use a server, can you please explain how I will have to do it since I haven't done something similar. So, I will have to have browser-based UI talking to server and server talking to Unreal right? In that case, should I have a nodejs server for example receiving the messages and then broadcasting them somehow?

**Comment by colinbdclark** [comment]
Yes, it sounds like you'll want some kind of server that can accept Web Socket requests from your browser-based client and forward them on to your Unreal application using your preferred protocol (usually OSC messages are sent over UDP).

You can see an example of this in the [osc.js-examples repository](https://github.com/colinbdclark/osc.js-examples/tree/master/browser). The example opens an <code>osc.UDPPort</code> to an application and creates a Web Socket Server and corresponding <code>osc.WebSocketPort</code> for the browser-based client. And then it associates the two Port objects using an <code>osc.relay</code>, which will automatically forward messages at either end of the relay to the other.

**Comment by sinokgr** [comment]
good, thanks for the help. 👍
